{{- if .Values.appwrite.usageStats.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "appwrite.fullname" $ }}-usage"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
    app.kubernetes.io/component: usage
spec:
  selector:
    matchLabels:
{{ include "appwrite.selectorLabels" $ | indent 6 }}
      app.kubernetes.io/component: usage
  replicas: 1
  template:
    metadata:
      labels:
{{ include "appwrite.labels" $ | indent 8 }}
        app.kubernetes.io/component: usage
      annotations:
        checksum/config-env: {{ include (print $.Template.BasePath "/config/env.yaml") . | sha256sum }}
        checksum/secrets-env: {{ include (print $.Template.BasePath "/secrets/env.yaml") . | sha256sum }}
        checksum/secrets-db: {{ include (print $.Template.BasePath "/secrets/db.yaml") . | sha256sum }}
        checksum/secrets-redis: {{ include (print $.Template.BasePath "/secrets/redis.yaml") . | sha256sum }}
    spec:
      initContainers:
      {{- include "redisCheck" $ | nindent 6 }}
      containers:
      - name: appwrite-usage
        image: "{{ .Values.appwrite.image.repository }}:{{ .Values.appwrite.image.tag | default .Chart.AppVersion }}"
        command:
          - "usage"
        {{- with .Values.appwrite.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "appwrite.fullname" $ }}-env
        - secretRef:
            name: {{ include "appwrite.fullname" $ }}-env
        - secretRef:
            name: {{ include "appwrite.fullname" $ }}-db-env
        - secretRef:
            name: {{ include "appwrite.fullname" $ }}-redis-env
{{- end }}
