  
language: node_js
node_js:
  - "14.16"

jobs:
  include:
    - stage: npm release
      node_js: "14.16"
      script: 
        - echo "Installing dependencies ..."
        - npm i
        - echo "Building library ..."
        - npm run build
        - echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true
