language: php

php:
  - '7.3'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - eldad@appwrite.io

services:
- docker

before_install:
- composer update --ignore-platform-reqs --optimize-autoloader --no-dev --no-plugins --no-scripts

install:
- docker-compose -f tests/resources/docker-compose.yml up -d
- sleep 60

script:
- php -v
- ls storage
- ls tests/reosurces/storage