language: php

php:
  - '7.4'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

# cache:
#   directories:
#   - docker_images

# before_install:
# - docker load -i docker_images/images.tar || true

# before_cache:
# - docker save -o docker_images/images.tar appwrite_appwrite

install:
- docker-compose up -d
- sleep 90

script:
- docker ps
- docker exec appwrite test