services:
  appwrite:
    container_name: appwrite
    image: appwrite-dev
    build:
      context: .
      args:
        - DEBUG=false
        - TESTING=true
        - VERSION=dev

  appwrite-realtime:
    image: appwrite-dev

  appwrite-worker-audits:
    image: appwrite-dev

  appwrite-worker-webhooks:
    image: appwrite-dev

  appwrite-worker-deletes:
    image: appwrite-dev

  appwrite-worker-databases:
    image: appwrite-dev

  appwrite-worker-builds:
    image: appwrite-dev

  appwrite-worker-certificates:
    image: appwrite-dev

  appwrite-worker-functions:
    image: appwrite-dev

  appwrite-executor:
    image: appwrite-dev

  appwrite-worker-mails:
    image: appwrite-dev

  appwrite-worker-messaging:
    image: appwrite-dev

  appwrite-maintenance:
    image: appwrite-dev

  appwrite-usage-timeseries:
    image: appwrite-dev

  appwrite-usage-database:
    image: appwrite-dev

  appwrite-schedule:
    image: appwrite-dev
