name: "Static code analysis"

on: [pull_request]
jobs:
  lint:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Run CodeQL
      run: |
        docker run --rm -v $PWD:/app composer:2.6 sh -c \
        "composer install --profile --ignore-platform-reqs && composer check"
    
    - name: Run Locale check
      run: |
        docker run --rm -v $PWD:/app node:24-alpine sh -c \
        "cd /app/.github/workflows/static-analysis/locale && node index.js"
